AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
 # General Name Tag
  NameTagConfigRule:
    Type: "AWS::Config::ConfigRule"
    Properties:
      InputParameters:
        tag1Key: Name
      ConfigRuleName: "required-name-tags"
      Source: 
        Owner: "AWS"
        SourceIdentifier: "REQUIRED_TAGS"
      Description: "Checks whether your resources have the tags that you specify"
      Scope: 
        ComplianceResourceTypes: 
        # 上限100リソースタイプらしい #
        - AWS::AutoScaling::AutoScalingGroup
        - AWS::CloudFormation::Stack
        - AWS::CloudTrail::Trail
        - AWS::CloudWatch::Alarm
        - AWS::EC2::FlowLog
        - AWS::EC2::Instance
        - AWS::EC2::InternetGateway
        - AWS::EC2::NatGateway
        - AWS::EC2::NetworkAcl
        - AWS::EC2::NetworkInterface
        - AWS::EC2::RouteTable
        - AWS::EC2::SecurityGroup
        - AWS::EC2::Subnet
        - AWS::EC2::TransitGateway
        - AWS::EC2::VPC
        - AWS::EC2::VPCEndpoint
        - AWS::EC2::VPNConnection
        - AWS::EC2::VPNGateway
        - AWS::EC2::Volume
        - AWS::ElasticLoadBalancing::LoadBalancer
        - AWS::ElasticLoadBalancingV2::LoadBalancer
        - AWS::RDS::DBCluster
        - AWS::RDS::DBClusterSnapshot
        - AWS::RDS::DBInstance
        - AWS::RDS::DBSecurityGroup
        - AWS::RDS::DBSnapshot
        - AWS::RDS::DBSubnetGroup
        - AWS::RDS::EventSubscription
        - AWS::Redshift::Cluster
        - AWS::Redshift::ClusterParameterGroup
        - AWS::Redshift::ClusterSecurityGroup
        - AWS::Redshift::ClusterSnapshot
        - AWS::Redshift::ClusterSubnetGroup
        - AWS::Redshift::EventSubscription
        - AWS::S3::Bucket
        - AWS::SNS::Topic
        - AWS::KMS::Key


## EC2 Purpose Tag
  PurposeTagConfigRule:
    Type: "AWS::Config::ConfigRule"
    Properties:
      InputParameters:
        tag1Key: Purpose
      ConfigRuleName: "required-purpose-tags"
      Source: 
        Owner: "AWS"
        SourceIdentifier: "REQUIRED_TAGS"
      Description: "Checks whether your resources have the tags that you specify"
      Scope: 
        ComplianceResourceTypes: 
        - AWS::EC2::Instance
        - AWS::EC2::Volume
