AWSTemplateFormatVersion: '2010-09-09'
Resources:
  OrgConfigRuleNameTag:
    Type: AWS::Config::OrganizationConfigRule
    Properties:
      OrganizationConfigRuleName: "required-name-tag"
      OrganizationManagedRuleMetadata: 
        Description: "use REQUIRED_TAGS"
        InputParameters: '{"tag1Key":"Name"}'
        # MaximumExecutionFrequency: Strinxg

        # 上限100リソースタイプらしい #
        ResourceTypesScope: 
          - AWS::AutoScaling::AutoScalingGroup
          - AWS::CloudFormation::Stack
          - AWS::CloudTrail::Trail
          - AWS::CloudWatch::Alarm
          - AWS::EC2::FlowLog
          - AWS::EC2::Instance
          - AWS::EC2::InternetGateway
          - AWS::EC2::NatGateway
          - AWS::EC2::NetworkAcl
          - AWS::EC2::NetworkInterface
          - AWS::EC2::RouteTable
          - AWS::EC2::SecurityGroup
          - AWS::EC2::Subnet
          - AWS::EC2::TransitGateway
          - AWS::EC2::VPC
          - AWS::EC2::VPCEndpoint
          - AWS::EC2::VPNConnection
          - AWS::EC2::VPNGateway
          - AWS::EC2::Volume
          - AWS::ElasticLoadBalancing::LoadBalancer
          - AWS::ElasticLoadBalancingV2::LoadBalancer
          - AWS::RDS::DBCluster
          - AWS::RDS::DBClusterSnapshot
          - AWS::RDS::DBInstance
          - AWS::RDS::DBSecurityGroup
          - AWS::RDS::DBSnapshot
          - AWS::RDS::DBSubnetGroup
          - AWS::RDS::EventSubscription
          - AWS::Redshift::Cluster
          - AWS::Redshift::ClusterParameterGroup
          - AWS::Redshift::ClusterSecurityGroup
          - AWS::Redshift::ClusterSnapshot
          - AWS::Redshift::ClusterSubnetGroup
          - AWS::Redshift::EventSubscription
          - AWS::S3::Bucket
          - AWS::SNS::Topic
          - AWS::KMS::Key
        RuleIdentifier: REQUIRED_TAGS