AWSTemplateFormatVersion: '2010-09-09'
Resources:

  OrgConfigRulePurposeTag:
    Type: AWS::Config::OrganizationConfigRule
    Properties:
      OrganizationConfigRuleName: "required-purpose-tag"
      OrganizationManagedRuleMetadata: 
        Description: "use REQUIRED_TAGS"
        InputParameters: '{"tag1Key":"Purpose"}'
        # MaximumExecutionFrequency: Strinxg
        ResourceTypesScope: 
          - AWS::EC2::Instance
          - AWS::EC2::Volume
        RuleIdentifier: REQUIRED_TAGS
